version: '3.8'

services:
  hebrew-intel:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HEBSPACY_MODEL=he
      - CACHE_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=false
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    volumes:
      - hebrew-models:/app/models/model_cache
      - ./logs:/app/logs
    networks:
      - intelligence-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - intelligence-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hebrew-models:
    driver: local
  redis-data:
    driver: local

networks:
  intelligence-network:
    driver: bridge
